---
apiVersion: v1
binaryData:
  generateServiceMonitor-hook.sh: ""
kind: ConfigMap
metadata:
  name: shell-operator-hooks
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shell-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: shell-operator
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-operator
  namespace: default
  labels:
    app: shell-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-operator
  template:
    metadata:
      labels:
        app: shell-operator
    spec:
      containers:
        - name: shell-operator
          env:
            - name: CLUSTER
              value: kubernetes
            - name: METRICS
              value: metrics prometheus
          image: "flant/shell-operator:v1.2.0"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: hooks
              mountPath: /hooks
      serviceAccountName: shell-operator
      serviceAccount: shell-operator
      volumes:
        - name: hooks
          configMap:
            name: shell-operator-hooks
            defaultMode: 0777
