---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: burrow
  name: burrow
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: burrow
