#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd "$SCRIPT_DIR"

CACHED="$SCRIPT_DIR/chart"
DEFAULT_VERSION="0.27.1"
DEFAULT_NAMESPACE="kafka"

INPUT=${1?Please input \"$DEFAULT_VERSION\" | \"build [$DEFAULT_NAMESPACE(namespace)]\"}
NAMESPACE=${2:-$DEFAULT_NAMESPACE}

command -v kustomize >/dev/null || {
  KUSTOMIZE_VERSION="4.5.3"
  wget -O- "https://ghproxy.com/https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v$KUSTOMIZE_VERSION/kustomize_v${KUSTOMIZE_VERSION}_$(uname)_amd64.tar.gz" | tar -xz
  mv kustomize "${PATH%%:*}"
}

case $INPUT in
build)
  KUSTOMIZATION="$SCRIPT_DIR/kustomization.yml"
  $(which rm) -f "${KUSTOMIZATION%.*}"*
  cat <<EOF >"$KUSTOMIZATION"
helmCharts:
  - name: chart
    Namespace: ""
    releaseName: strimzi-kafka-operator
    ValuesFile: ""
    ValuesInline:
      tmpDirSizeLimit: 5Mi
    ValuesMerge: override # merge, override, replace
    includeCRDs: true
helmGlobals:
  chartHome: .
namespace: $NAMESPACE
EOF
  kustomize build "${KUSTOMIZATION%/*}" --enable-helm
  ;;
*)
  VERSION="$INPUT"
  TARGET_REPO="strimzi/strimzi-kafka-operator"
  TARGET_PATH="strimzi-kafka-operator"
  wget -O- "https://ghproxy.com/https://github.com/$TARGET_REPO/releases/download/$VERSION/strimzi-kafka-operator-helm-3-chart-$VERSION.tgz" |
    tar -xz "$TARGET_PATH"
  $(which rm) -rf "$CACHED"
  mv "$TARGET_PATH" "$CACHED"
  $(which rm) -rf "${TARGET_PATH%%/*}"
  ;;
esac

which helm || {
  echo -e "Please INSTALL helm:\n\thttps://github.com/helm/helm/releases"
  exit
  helm -n kafka install kafka "$DIR/chart"
}
