apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaas-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  revisionHistoryLimit: 3
  source:
    path: .
    plugin:
      name: vaas-app
    repoURL: git@gitlab.xxxx.com:appstore/cluster-xxxx/app.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - Replace=true
