{{- $namespace := .Release.Namespace }}
{{- range $idx, $value := .Values.instances }}
{{- if $value.enabled }}
{{- $runEnv := default "prod" $value.runEnv }}
{{- if regexFind "^[vs]ms-(dev|test)$" $namespace }}
{{- $runEnv = printf "%s%d" $runEnv 1 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if hasSuffix "template-test" $value.name }}
  name: {{ $value.name }}-{{randNumeric 10}}
  {{- else }}
  name: {{ $value.name }}
  {{- end }}
  namespace: {{ $namespace }}
{{- if $value.binaryData }}
binaryData:
  {{- range $key, $val := $value.binaryData }}
  {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}
{{- if $value.data }}
data:
{{- range $key, $val := $value.data }}
  {{- if eq "prod" $runEnv }}
  {{ $key }}: {{ $val | toString | replace "runNamespace" $namespace | replace "runEnv" $runEnv | replace "run26Env" (regexFind "[a-z]+" $runEnv) | replace "_runExtEnv" "" | replace "-runExtEnv" "" | replace "_runExt26Env" "" | replace "-runExt26Env" "" | quote }}
  {{- else }}
  {{ $key }}: {{ $val | toString | replace "runNamespace" $namespace | replace "runEnv" $runEnv | replace "run26Env" (regexFind "[a-z]+" $runEnv) | replace "runExtEnv" $runEnv | replace "runExt26Env" (regexFind "[a-z]+" $runEnv) | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
