apiVersion: v1
name: Secret
version: 2022.1.11
appVersion: 1.1.1
description: Secret
keywords:
  - Secret
home: https://kubernetes.io/
sources:
  - https://kubernetes.io/docs/concepts/configuration/secret/
maintainers:
  - name: kubernetes
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png