version: '2'

services:

  elasticsearch:
    image: muicoder/alpine:elk-e
    hostname: elasticsearch
    command: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: muicoder/alpine:elk-l
    hostname: logstash
    command: logstash --http.host 0.0.0.0 -f pipeline/logstash.conf
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 5000:5000
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: muicoder/alpine:elk-k
    hostname: kibana
    command: kibana --host 0.0.0.0 --elasticsearch http://elasticsearch:9200
    ports:
      - 5601:5601

    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
