instances:
  - name: cors
    spec:
      headers:
        accessControlAllowHeaders:
          - '*'
        accessControlAllowMethods:
          - '*'
        accessControlAllowOriginList:
          - '*'
