apiVersion: v1
name: ConfigMap
version: 2022.1.11
appVersion: 1.1.1
description: ConfigMap
keywords:
  - ConfigMap
home: https://kubernetes.io/
sources:
  - https://kubernetes.io/docs/concepts/configuration/configmap/
maintainers:
  - name: kubernetes
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png