jobs:
  repo-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |-
            CACHE_IMAGE=${{ inputs.CACHE_IMAGE }}
            CACHE_VERSION=${{ inputs.CACHE_VERSION }}
          context: .
          file: argocd.Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/argocd-operator:plugins
name: buildImage::argocd-plugins
on:
  workflow_dispatch:
    inputs:
      CACHE_IMAGE:
        default: ghcr.io/helmfile/helmfile
        description: image name
        required: true
        type: string
      CACHE_VERSION:
        default: canary
        description: image tag
        required: true
        type: string
